---
- name: populate service facts
  service_facts:

- name: Stop services
  service:
    name: "{{ item }}"
    state: stopped
  loop:
  - vdsmd.service
  - supervdsmd.service
  - libvirtd.service
  - ovirt-imageio.service
  - NetworkManager.service
  when: "item in ansible_facts.services"

- name: Start and enable services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
  # vdsmd will start all its dependent services stopped earlier, libvirtd, ovirt-imageio, supervdsmd
  - cgconfig.service
  - messagebus.service
  - NetworkManager.service
  - vdsmd.service
  when: "item in ansible_facts.services"
